### ISSUE TITLE
Transaction bug when exchanging an asset (app.emeris.com)

### ISSUE THREAD

**Issue by ghost** [gnuclear/gnuclear-whitepaper#126]
I can't exchange an **ATOM** for  **CRO** here https://app.emeris.com/
As a result, I do not receive anything and the commission is burned.

https://www.mintscan.io/cosmos/txs/12A3160B0EAA49D92A58EBE3121A13FB69982F0616F6911C507B1D0948CE9F7B
https://www.mintscan.io/cosmos/txs/9B28C80947212758899E7C01A3D5F0C0B4CEB58EE95CE9DD86007101B91CD91E
https://www.mintscan.io/cosmos/txs/C3CA385782CF79EF44AF3AAF82B4BFC6B47972CE222ADB8C9A82565C56586EFD
https://www.mintscan.io/cosmos/txs/C99F5ABDA65BBC1AC7BD510E37D36DA75D9FEEA2888911F9C73E6DDCC02C4BF0

https://www.mintscan.io/cosmos/txs/8F54B67F9AA3BEA9C349F393317B246E805D71E7755F7EE92B4BCAED3EFB590B

**Comment by dongsam** [comment]
Hi, When analyzing [block_result's](http://78.46.243.107:26657/block_results?height=7654402) swap_transacted event for transaction [C99F5ABDA65BBC1AC7BD510E37D36DA75D9FEEA2888911F9C73E6DDCC02C4BF0](https://www.mintscan.io/cosmos/txs/C99F5ABDA65BBC1AC7BD510E37D36DA75D9FEEA2888911F9C73E6DDCC02C4BF0),

the swap tx was failed in batch stage because the requested  `order_price`(`21717.390869999999267748`) was higher than `swap_price`(`21635.548999405792868217`) and `offer_coin_amount`(1000000) + `reserved_offer_coin_fee_amount`(1500) refunded as well on the end block.

currently, you can set advanced functionality to set a custom slippage (i.e. a limit price, order_price) in the Emeris app or manual tx. If the swap sets the price better than the expected swap_price, it can be transacted.

```json
[
  {
    "type": "swap_transacted",
    "attributes": [
      {
        "key": "pool_id",
        "value": "9",
        "index": true
      },
      {
        "key": "batch_index",
        "value": "1849",
        "index": true
      },
      {
        "key": "msg_index",
        "value": "1632",
        "index": true
      },
      {
        "key": "swap_requester",
        "value": "cosmos19wtkh935tx2ut2n4m6tjvkfvew4shaeep6td8u",
        "index": true
      },
      {
        "key": "swap_type_id",
        "value": "1",
        "index": true
      },
      {
        "key": "offer_coin_denom",
        "value": "uatom",
        "index": true
      },
      {
        "key": "offer_coin_amount",
        "value": "1000000",
        "index": true
      },
      {
        "key": "demand_coin_denom",
        "value": "ibc/C932ADFE2B4216397A4F17458B6E4468499B86C3BC8116180F85D799D6F5CC1B",
        "index": true
      },
      {
        "key": "order_price",
        "value": "21717.390869999999267748",
        "index": true
      },
      {
        "key": "swap_price",
        "value": "21635.548999405792868217",
        "index": true
      },
      {
        "key": "remaining_offer_coin_amount",
        "value": "1000000",
        "index": true
      },
      {
        "key": "exchanged_offer_coin_amount",
        "value": "0",
        "index": true
      },
      {
        "key": "reserved_offer_coin_fee_amount",
        "value": "1500",
        "index": true
      },
      {
        "key": "order_expiry_height",
        "value": "7654402",
        "index": true
      },
      {
        "key": "success",
        "value": "failure",
        "index": true
      }
    ]
  },
  {
    "type": "message",
    "attributes": [
      {
        "key": "sender",
        "value": "cosmos1tx68a8k9yz54z06qfve9l2zxvgsz4ka3hr8962",
        "index": true
      }
    ]
  },
  {
    "type": "transfer",
    "attributes": [
      {
        "key": "recipient",
        "value": "cosmos19wtkh935tx2ut2n4m6tjvkfvew4shaeep6td8u",
        "index": true
      },
      {
        "key": "amount",
        "value": "1001500uatom",
        "index": true
      }
    ]
  }
]
```

**Comment by dongsam** [comment]
I left a comment here https://github.com/tendermint/liquidity/issues/444#issuecomment-928695511
